# Generated by Django 4.2.16 on 2026-01-20 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3)),
                ('recipient_details', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='payouts_pay_status_a5ad2e_idx'), models.Index(fields=['created_at'], name='payouts_pay_created_b65d12_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payout_amount_positive'),
        ),
    ]
